import {useEffect,useRef,useState} from 'react';
import {api} from '../api';
import {DisplayText} from './Text';
import type {Act} from './WorkDrawers';
import type {Effects,Snapshot} from '../types';
export function Settings({data,act,effects,onEffects}:{data:Snapshot;act:Act;effects:Effects;onEffects:(e:Effects)=>void}){
 const s=data.settings;const [dirty,setDirty]=useState(false),[scale,setScale]=useState(s.scale_percent),form=useRef<HTMLFormElement>(null);
 useEffect(()=>{if(!dirty)setScale(s.scale_percent);},[s.scale_percent,dirty]);
 const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const values=new FormData(event.currentTarget);await api('save_settings',{listen_port:Number(values.get('port')),approval_timeout_seconds:Number(values.get('approval')),max_command_timeout_seconds:Number(values.get('timeout')),output_limit_bytes:Number(values.get('output')),ui:{effects,motion_enabled:effects!=='off',scale_percent:scale}});setDirty(false);};
 return <section id="page-settings"><div className="config-section"><h3>命令准入</h3><div className="setting-switch"><div><strong>自动允许只读命令</strong><p>按工具、参数和服务器策略放行。</p></div><label className="switch"><input id="readonly-switch" type="checkbox" checked={s.auto_allow_readonly} onChange={e=>void act(()=>api('set_readonly',e.target.checked))}/><span/></label></div><div className="command-chips">{['ls','ll','cat','tail','head','pwd','wc','grep','find','stat / du / df','ps / free / uname','git status / log / diff','docker ps / logs / inspect'].map(t=><code key={t}>{t}</code>)}</div><p className="inline-help">管道、写入、重定向、组合命令和多行脚本仍需审批。</p></div>
  <div className="config-section"><h3>显示</h3><label>特效强度<select id="effects-select" value={effects} onChange={e=>onEffects(e.target.value as Effects)}><option value="standard">标准</option><option value="low">低</option><option value="off">关</option></select></label><p className="inline-help">系统开启“减少动态效果”时，标准档按低档运行。关闭后仍保留静态背景。</p><label>文字缩放 <span id="scale-value" className="mono">{scale}%</span><input id="ui-scale" type="range" min="90" max="130" step="5" value={scale} onChange={e=>{const value=Number(e.target.value);setScale(value);setDirty(true);document.documentElement.style.setProperty('--font-scale',String(value/100));}}/></label></div>
  <div className="config-section"><h3>执行限制</h3><form id="settings-form" ref={form} onChange={()=>setDirty(true)} onSubmit={e=>void act(()=>submit(e),'设置已保存')}><div className="form-grid"><label>待审有效期 / 秒<input name="approval" id="setting-approval-timeout" type="number" min="10" max="3600" defaultValue={s.approval_timeout_seconds} required/></label><label>命令最长时间 / 秒<input name="timeout" id="setting-command-timeout" type="number" min="1" max="86400" defaultValue={s.max_command_timeout_seconds} required/></label><label>输出保存上限<select name="output" id="setting-output" defaultValue={s.output_limit_bytes}>{[...new Set([4096,1048576,2097152,4194304,s.output_limit_bytes])].map(n=><option key={n} value={n}>{n>=1048576?n/1048576+' MiB':n/1024+' KiB'}</option>)}</select></label><label>本地 MCP 端口<input name="port" id="setting-port" type="number" min="1024" max="65535" defaultValue={s.listen_port} required/></label></div><p className="inline-help">更改端口前，先停止隧道并处理未完成请求。</p><button type="submit" className="button primary">保存设置{dirty?' *':''}</button></form></div>
  <div className="config-section service-panel"><div><h3>MCP 服务</h3><code id="settings-endpoint">{data.mcp.endpoint}</code><p className="inline-help" id="config-location">本地配置：{s.config_path}</p></div><button className="button" id="mcp-control" onClick={()=>void act(()=>api('set_mcp_running',!data.mcp.running))}>{data.mcp.running?'停止接入':'启动服务'}</button></div>
 </section>;
}
export function Tunnel({data,act}:{data:Snapshot;act:Act}){
 const t=data.tunnel,form=useRef<HTMLFormElement>(null),key=useRef<HTMLInputElement>(null),[dirty,setDirty]=useState(false),[mode,setMode]=useState(t.proxy_mode),[url,setUrl]=useState(t.proxy_url),[visible,setVisible]=useState(false),[remember,setRemember]=useState(true),[candidates,setCandidates]=useState(t.proxy_diagnostics?.result?.candidates||[]);
 const locked=t.running||t.download_status==='running',job=t.proxy_diagnostics;
 useEffect(()=>{if(!dirty){setMode(t.proxy_mode||'auto');setUrl(t.proxy_url||'');}},[t.proxy_mode,t.proxy_url,dirty]);
 useEffect(()=>{if(job?.kind==='detect'&&job.result?.candidates)setCandidates(job.result.candidates);},[job?.result]);
 const save=async()=>{const f=new FormData(form.current!);await api('save_tunnel',{id:String(f.get('id')||'').trim(),client_path:String(f.get('client_path')||'').trim(),health_port:Number(f.get('health_port')),proxy_mode:mode,proxy_url:mode==='manual'?url.trim():''});setDirty(false);};
 const result=job?.result,download={idle:t.client_exists?'已找到客户端。':'未找到客户端，请下载或选择。',running:'正在下载并校验官方发布包…',succeeded:'下载完成，SHA256 校验通过。',failed:'下载失败：'+t.download_error,cancelled:'下载已取消。'}[t.download_status]||t.download_status;
 const pick=async()=>{const path=await api('choose_file','tunnel_client');if(path&&form.current){(form.current.elements.namedItem('client_path') as HTMLInputElement).value=path;setDirty(true);}};
 return <section id="page-tunnel"><div className="section-heading"><p>Secure MCP Tunnel 接入</p><button className="button" id="open-diagnostics" disabled={!t.running} onClick={()=>void act(()=>api('open_external','diagnostics'))}>官方诊断页 ↗</button></div><div className="tunnel-route"><span>本地 MCP <small>{data.mcp.running?data.mcp.endpoint:'未启动'}</small></span><i/><span>Secure Tunnel <small>{t.ready?'已就绪':t.running?'连接中':'未启动'}</small></span><i/><span>ChatGPT <small>在 Chat 中启用插件</small></span></div>
  <form id="tunnel-form" ref={form} onChange={()=>setDirty(true)} onSubmit={e=>{e.preventDefault();void act(save,'隧道与代理配置已保存');}}><fieldset className="config-section" disabled={locked}><h3>连接配置</h3><label>Tunnel ID<input id="tunnel-id" name="id" defaultValue={t.id} placeholder="tunnel_…" autoComplete="off"/></label><label>客户端路径<div className="input-with-button"><input id="tunnel-client" name="client_path" defaultValue={t.client_path}/><button type="button" className="button" id="pick-client" onClick={()=>void act(pick)}>选择</button></div></label><label>本地诊断端口<input id="tunnel-port" name="health_port" type="number" min="1024" max="65535" defaultValue={t.health_port} required/></label><button type="submit" className="button primary">保存配置{dirty?' *':''}</button> <button type="button" className="text-button" id="download-client" onClick={()=>void act(async()=>{if(dirty)throw new Error('请先保存修改后的配置');await api('download_tunnel');})}>下载官方客户端</button><p className="inline-help" id="client-download-status">{download}</p></fieldset></form>
  <div className="config-section"><div className="section-subhead"><h3>运行控制</h3><small>{t.api_key_saved?'已保存运行密钥':'未保存运行密钥'}</small></div><label>OpenAI API Key<div className="input-with-button"><input id="tunnel-key" ref={key} type={visible?'text':'password'} autoComplete="off" placeholder={t.api_key_saved?'留空使用已保存的密钥':'输入用于 Secure Tunnel 的 API Key'} disabled={t.running}/><button className="button" id="toggle-tunnel-key" onClick={()=>setVisible(!visible)} aria-label="显示或隐藏密钥">{visible?'隐藏':'显示'}</button></div></label><label className="setting-switch compact"><div><strong>记住此密钥</strong><p>使用与 SSH 密码相同的 AES-256-GCM 本机凭据仓库，不写入 config.json。</p></div><span className="switch"><input id="remember-tunnel-key" type="checkbox" checked={remember} disabled={t.running} onChange={e=>setRemember(e.target.checked)}/><span/></span></label><div className="button-group"><button className="button primary" id="start-tunnel" disabled={t.running||!data.mcp.running||t.download_status==='running'} onClick={()=>void act(async()=>{if(dirty)throw new Error('请先保存修改后的配置');let secret=key.current?.value||'';if(key.current)key.current.value='';setVisible(false);try{await api('start_tunnel',secret,remember);}finally{secret='';}})}>启动隧道</button><button className="button" id="stop-tunnel" disabled={!t.running} onClick={()=>void act(()=>api('stop_tunnel'))}>停止隧道</button><button className="text-button" id="forget-tunnel-key" disabled={!t.api_key_saved} onClick={()=>void act(()=>api('clear_tunnel_api_key'),'已删除保存的运行密钥')}>删除已保存密钥</button><button className="text-button" id="open-tunnels" onClick={()=>void act(()=>api('open_external','tunnels'))}>隧道设置 ↗</button><button className="text-button" id="open-keys" onClick={()=>void act(()=>api('open_external','keys'))}>创建运行密钥 ↗</button></div></div>
  <div className="config-section" aria-labelledby="proxy-title"><h3 id="proxy-title">出站代理</h3><p className="inline-help">关闭 TUN 后，代理软件需继续提供 HTTP 或 Mixed 端口。</p><div id="proxy-form"><div className="form-grid"><label>代理模式<select id="proxy-mode" value={mode} disabled={locked} onChange={e=>{setMode(e.target.value as typeof mode);setDirty(true);}}><option value="auto">自动检测</option><option value="manual">手动指定</option><option value="direct">直连</option></select></label><label>HTTP / HTTPS 代理地址<input id="proxy-url" value={url} disabled={locked||mode!=='manual'} onChange={e=>{setUrl(e.target.value);setDirty(true);}} placeholder="http://127.0.0.1:7890"/></label></div><p className="inline-help">{mode==='auto'?'优先环境变量，再读取 Windows 系统代理与常见本地端口。':mode==='manual'?'填写代理软件的 HTTP/Mixed 地址。':'Tunnel 及客户端下载直接联网。'}</p><div className="button-group"><button className="button" id="save-proxy" disabled={locked} onClick={()=>void act(save,'代理设置已保存')}>保存代理设置</button><button className="button" id="detect-proxy" disabled={job?.state==='running'} onClick={()=>void act(()=>api('proxy_action','detect'))}>检测代理</button><button className="button primary" id="test-proxy" disabled={job?.state==='running'} onClick={()=>void act(()=>api('proxy_action','test',mode,url))}>测试 HTTPS 连接</button></div></div><p id="proxy-effective" className="inline-help">{t.proxy_route?`当前进程：${t.proxy_route.source} · ${t.proxy_route.url||'直连'}`:'启动后显示实际出站路由。'}</p><div id="proxy-candidates">{candidates.map((p,i)=><div className="proxy-candidate" key={i}><div><code>{p.url}</code><small>{p.source}</small></div><span className={'badge '+(p.usable?'blue':'amber')}>{p.usable?'CONNECT 通过':p.tcp?'TCP 已连':'TCP 未连接'}</span><button className="button" disabled={locked||(p.authenticated&&i!==0)} onClick={()=>{setMode(p.authenticated?'auto':'manual');setUrl(p.authenticated?'':p.url);setDirty(true);}}>{p.authenticated?'使用自动模式':'采用'}</button>{p.error&&<p className="error">{p.error}</p>}</div>)}</div><div className={'proxy-result '+(result?.ok===false?'failed':result?.ok?'passed':'')} id="proxy-result" role="status">{job?.state==='running'?`${job.phase||'正在检测'}…`:result?<><strong>{job?.kind==='test'?(result.ok?'HTTPS 连接通过':'HTTPS 连接未通过'):`检测到 ${result.candidates?.length||0} 个候选`}</strong><br/>{result.route&&`${result.route.source} · ${result.route.url||'直连'}`} {result.duration_ms!=null&&`${result.duration_ms} ms`} {result.http_status&&`HTTP ${result.http_status}`}<br/>{result.message||result.error}{result.warnings?.join('\n')}</>:'检测读取本地代理配置；HTTPS 测试不发送运行密钥。'}</div></div>
  <div className="config-section"><div className="section-subhead"><h3>客户端事件</h3><small>{t.ready_observed_at?'OBSERVED '+new Date(t.ready_observed_at*1000).toLocaleTimeString():'LOCAL'}</small></div><pre className="terminal-output" id="tunnel-logs"><DisplayText text={t.logs.join('\n')||'隧道尚未启动。'}/></pre></div>
 </section>;
}
