/* Production React assets + real DesktopAPI/ApprovalManager. No live SSH or Tunnel. */
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert'),{spawn}=require('child_process'),readline=require('readline');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'../frontend/node_modules/playwright');
const root=path.resolve(__dirname,'..'),output=process.env.SSH_UI_OUTPUT||path.join(root,'preview'),html=path.join(os.tmpdir(),'ssh-react-'+require('crypto').randomUUID()+'.html');fs.mkdirSync(output,{recursive:true});
const python=process.env.SSH_UI_PYTHON||path.join(root,'.venv',process.platform==='win32'?'Scripts':'bin',process.platform==='win32'?'python.exe':'python');
const child=spawn(python,['tests/fixture_desktop.py',html],{cwd:root,stdio:['pipe','pipe','pipe']});
let readyResolve,readyReject,next=1,stderr='',browser,page;const checks=[],errors=[],pending=new Map();
const ready=new Promise((resolve,reject)=>{readyResolve=resolve;readyReject=reject;});
child.stderr.on('data',c=>stderr+=c.toString());readline.createInterface({input:child.stdout}).on('line',line=>{try{const x=JSON.parse(line);if(x.ready)readyResolve(x);else{pending.get(x.id)?.resolve(x.result);pending.delete(x.id);}}catch(e){readyReject(e);}});
child.on('error',readyReject);child.on('exit',code=>{if(code){const e=new Error(stderr||'Fixture exited '+code);readyReject(e);for(const p of pending.values())p.reject(e);}});
const rpc=(method,args=[])=>new Promise((resolve,reject)=>{const id=next++;pending.set(id,{resolve,reject});child.stdin.write(JSON.stringify({id,method,args})+'\n');});
const methods=['snapshot','request_detail','begin_review','approve','reject','submit_local','set_readonly','known_hosts','save_connection','remove_connection','test_connection','disconnect_connection','answer_prompt','choose_file','export_output','save_settings','set_mcp_running','save_tunnel','start_tunnel','stop_tunnel','download_tunnel','open_external','filesystem','terminate_request','prepare_upload','save_download','clear_transfer','session_action','session_detail','ssh_profiles','preview_connection','proxy_action','revoke_authorization'];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const refresh=async()=>{await page.evaluate(()=>window.SSHUI.refresh());await sleep(100);};
const go=async name=>{await page.evaluate(name=>window.SSHUI.go(name),name);await page.locator('#page-'+name).waitFor();};
const close=async()=>{if(await page.locator('#drawer').count())await page.locator('#drawer-close').click();};
const capture=async name=>{await sleep(350);await page.screenshot({path:path.join(output,name+'.png')});};
const check=async(name,fn)=>{await fn();checks.push(name);console.log('PASS '+name);};
const waitStatus=async(id,status)=>{await page.waitForFunction(async([id,status])=>{const x=await window.desktopRPC('snapshot',[]);return x.data.requests.find(r=>r.request_id===id)?.status===status;},[id,status]);await refresh();};
const hold=async(id,ms=1800)=>{await close();const button=page.locator(`[data-request-id="${id}"] .hold`);await button.waitFor();await page.waitForFunction(id=>!document.querySelector(`[data-request-id="${id}"] .hold`).disabled,id);const box=await button.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await sleep(ms);await page.mouse.up();await refresh();};
(async()=>{
 const fixture=await ready;browser=await chromium.launch({headless:true,executablePath:process.env.SSH_UI_CHROME||undefined,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});
 page=await browser.newPage({viewport:{width:1400,height:900}});page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));await page.exposeFunction('desktopRPC',(method,args)=>rpc(method,args));
 await page.addInitScript(methods=>{window.pywebview={api:{}};for(const method of methods)window.pywebview.api[method]=(_token,...args)=>window.desktopRPC(method,args);},methods);
 await page.goto('file://'+fixture.html);await page.waitForFunction(()=>window.SSHUI&&document.querySelector('#bridge-label').textContent==='本地应用已连接');
 await check('React scene initializes with real snapshot and complete approval reasons',async()=>{await page.locator('.gate-item.destructive .hold:not([disabled])').waitFor();await page.waitForFunction(()=>document.querySelector('#term').textContent.includes('ls -lah'));assert.equal(await page.locator('#hud-nodes').textContent(),'3 servers');assert.equal(await page.locator('.gate-item').count(),2);assert((await page.locator('#gate-list').textContent()).includes('git reset --hard'));assert.equal((await page.evaluate(()=>window.SSHUI.diagnostics())).react,true);await capture('scene-overview');});
 const initial=(await rpc('snapshot')).data.requests;const destructive=initial.find(r=>r.command_preview==='git reset --hard').request_id,other=initial.find(r=>r.server_id==='logs'&&r.status==='pending_approval').request_id;
 await check('link bar animates real MCP calls and SSH dispatch only',async()=>{await refresh();assert.equal(await page.locator('#seg-mcp .pulse').count(),0);await rpc('fixture_mcp_traffic');await refresh();await page.locator('#chain-mcp .ping').waitFor({state:'attached'});assert.equal(await page.locator('#seg-tunnel .pulse').count(),0);const r=(await rpc('submit_local',['stage','pwd','链路动效测试','',300])).data;await refresh();await waitStatus(r.request_id,'succeeded');await page.waitForFunction(()=>document.querySelector('#chain-ssh .ping'));await capture('scene-link-traffic');});
 await check('release before 0.5 second hold threshold does not execute',async()=>{await hold(destructive,150);assert.equal((await rpc('snapshot')).data.requests.find(r=>r.request_id===destructive).status,'pending_approval');});
 await check('switching approval with keyboard cancels a held request',async()=>{await page.locator(`[data-request-id="${other}"]`).click();await page.keyboard.down('a');await sleep(150);await page.keyboard.press('j');await sleep(700);await page.keyboard.up('a');assert.equal((await rpc('snapshot')).data.requests.find(r=>r.request_id===other).status,'pending_approval');});
 await check('destructive 0.5 second hold grants one request and completes',async()=>{await hold(destructive,800);await waitStatus(destructive,'succeeded');assert.equal((await rpc('begin_review',[destructive])).ok,false);});
 await check('keyboard rejection affects only selected request',async()=>{await page.locator(`[data-request-id="${other}"]`).click();await page.keyboard.press('r');await waitStatus(other,'denied');await capture('scene-terrain');});
 await check('server node focus filters terminal and toggles back to all',async()=>{await page.locator('[data-server="logs"]').click();assert((await page.locator('#term-focus').textContent()).includes('logs'));assert(!(await page.locator('#term').textContent()).includes('git reset --hard'));await page.locator('[data-server="logs"]').click();assert((await page.locator('#term-focus').textContent()).includes('all'));});
 await check('Ctrl K searches servers and opens file drawer',async()=>{await page.keyboard.press('Control+k');await page.locator('#palette-input').fill('日志节点');await page.keyboard.press('Enter');assert((await page.locator('#term-focus').textContent()).includes('logs'));await page.locator('#focus-clear').click();await page.keyboard.press('Control+k');await page.locator('#palette-input').fill('浏览文件');await page.keyboard.press('Enter');await page.locator('#page-files').waitFor();await capture('scene-files');await close();});
 await check('node context menu opens server policy',async()=>{await page.locator('[data-server="stage"]').click({button:'right'});await page.getByRole('menuitem',{name:'服务器策略'}).click();await page.getByRole('heading',{name:'编辑服务器连接'}).waitFor();assert(await page.locator('#policy-default').isChecked());await page.getByRole('button',{name:'关闭对话框'}).click();});
 await check('new connection uses known hosts and survives local password flow',async()=>{await go('connections');await page.locator('[data-action="new-connection"]').click();await page.locator('#known-select').selectOption('0');assert.equal(await page.locator('#conn-host').inputValue(),'password.fixture');assert.equal(await page.locator('#conn-port').inputValue(),'2222');await page.locator('#conn-id').fill('ui-test');await page.locator('#conn-label').fill('交互验证节点');await page.locator('#conn-user').fill('fixture');await page.getByRole('button',{name:'保存并测试',exact:true}).click();await page.getByRole('heading',{name:'确认新的主机指纹'}).waitFor();await capture('scene-host-verification');await page.getByRole('button',{name:'仅本次会话信任',exact:true}).click();await page.getByRole('heading',{name:'SSH 本地登录'}).waitFor();await page.locator('#ssh-secret').fill('fixture-private-password');await page.getByRole('button',{name:'登录',exact:true}).click();await page.waitForSelector('#modal',{state:'detached'});await sleep(400);await refresh();assert(!JSON.stringify((await rpc('snapshot')).data).includes('fixture-private-password'));});
 await check('SSH profile clears overrides and previews jump route',async()=>{await go('connections');await page.locator('[data-action="new-connection"]').click();await page.locator('#ssh-profile-select option[value="10.208.88.201"]').waitFor({state:'attached'});await page.locator('#conn-user').fill('override');await page.locator('#conn-port').fill('9999');await page.locator('#conn-identity').fill('wrong-key');await page.locator('#ssh-profile-select').selectOption('10.208.88.201');for(const id of ['conn-user','conn-port','conn-identity'])assert.equal(await page.locator('#'+id).inputValue(),'');await page.locator('#preview-ssh').click();await page.waitForFunction(()=>document.querySelector('#ssh-route-preview')?.textContent.includes('12138'));const text=await page.locator('#ssh-route-preview').textContent();assert(text.includes('181'));assert(text.includes('quhanshi'));assert(text.includes('IdentitiesOnly yes'));await capture('scene-ssh-route');await page.getByRole('button',{name:'关闭对话框'}).click();});
 await check('structured file browser and HTML-like preview remain escaped',async()=>{await go('files');await page.locator('#fs-path').fill('/data');await page.locator('#fs-list').click();await page.waitForFunction(()=>document.querySelector('#fs-entries').textContent.includes('test.log'));await page.locator('[data-action="fs-entry"]').filter({hasText:'test.log'}).click();await page.waitForFunction(()=>document.querySelector('#fs-preview').textContent.includes('fixture log'));assert.equal(await page.locator('#fs-preview img').count(),0);await page.locator('#fs-path').fill('/data');await page.locator('#fs-find').click();await page.waitForFunction(()=>document.querySelector('#fs-entries').textContent.includes('data-evaluation'));await capture('scene-files');});
 await check('download cache can be saved through native file dialog fixture',async()=>{await page.locator('#fs-path').fill('/data/test.log');await page.locator('#fs-download').click();await page.waitForFunction(()=>document.querySelector('#transfer-list').textContent.includes('SHA256 已校验'));await page.getByRole('button',{name:'另存为',exact:true}).click();await sleep(250);assert.equal(fs.readFileSync(path.join(fixture.root,'export.txt'),'utf8'),'fixture download');});
 await check('staged upload waits for hold approval and shows transfer result',async()=>{await page.locator('#fs-upload').click();await page.getByRole('heading',{name:'上传到服务器',exact:true}).waitFor();await page.locator('#up-path').fill('/data/uploaded.log');await page.getByRole('button',{name:'提交上传审批',exact:true}).click();await page.waitForSelector('#modal',{state:'detached'});await refresh();const r=(await rpc('snapshot')).data.requests.find(r=>r.operation==='upload_file');assert.equal(r.status,'pending_approval');await hold(r.request_id,1400);await waitStatus(r.request_id,'succeeded');});
 await check('server policy categories and authorized roots persist',async()=>{await go('connections');await page.locator('[data-action="edit-connection"][data-id="stage"]').click();await page.locator('details').filter({hasText:'此服务器的自动授权类别与目录'}).locator('summary').click();await page.locator('#policy-default').uncheck();await page.locator('input[name="category"][value="diagnostics"]').check();await page.locator('#policy-roots').fill('/var/log');await page.getByRole('button',{name:'仅保存',exact:true}).click();await page.waitForSelector('#modal',{state:'detached'});const s=(await rpc('snapshot')).data.servers.find(s=>s.id==='stage');assert.deepEqual(s.auto_categories,['diagnostics']);assert.deepEqual(s.auto_roots,['/var/log']);});
 await check('controlled session context and execution reuse approval flow',async()=>{await go('sessions');await page.locator('#session-create').click();await page.locator('#session-cwd').fill('/data/project');await page.locator('#session-env').fill('{"PROJECT_MODE":"test"}');await page.getByRole('button',{name:'提交上下文审批',exact:true}).click();await page.waitForSelector('#modal',{state:'detached'});const r=(await rpc('snapshot')).data.requests.find(r=>r.operation==='create_session');await hold(r.request_id,1400);await waitStatus(r.request_id,'succeeded');await go('sessions');await page.waitForFunction(()=>document.querySelector('#session-list').textContent.includes('PROJECT_MODE'));await capture('scene-sessions');await page.locator('[data-action="exec-session"]').click();await page.locator('#session-command').fill('pwd');await page.getByRole('button',{name:'提交请求',exact:true}).click();await page.waitForSelector('#modal',{state:'detached'});await refresh();const command=(await rpc('snapshot')).data.requests.find(r=>r.command_preview.includes('export PROJECT_MODE=test'));assert(command);await rpc('reject',[command.request_id]);await refresh();});
 await check('proxy detection adoption and HTTPS diagnosis use existing API',async()=>{await go('tunnel');await page.locator('#detect-proxy').click();await page.waitForFunction(()=>document.querySelector('#proxy-candidates').textContent.includes('CONNECT 通过'));await page.getByRole('button',{name:'采用',exact:true}).click();assert.equal(await page.locator('#proxy-mode').inputValue(),'manual');assert.equal(await page.locator('#proxy-url').inputValue(),'http://127.0.0.1:7890');await page.locator('#save-proxy').click();await refresh();assert.equal((await rpc('snapshot')).data.tunnel.proxy_mode,'manual');await page.locator('#test-proxy').click();await page.waitForFunction(()=>document.querySelector('#proxy-result').textContent.includes('HTTP 401'));await capture('scene-proxy');await page.locator('#proxy-url').fill('http://127.0.0.1:7891');await page.locator('#test-proxy').click();await page.waitForFunction(()=>document.querySelector('#proxy-result').textContent.includes('HTTPS 连接未通过'));await page.locator('#proxy-url').fill('http://127.0.0.1:7890');await page.locator('#save-proxy').click();await refresh();});
 await check('tunnel starts clears runtime key locks configuration and stops',async()=>{await page.locator('#tunnel-id').fill('tunnel_'+'a'.repeat(32));await page.locator('#tunnel-form button[type="submit"]').click();await refresh();await page.locator('#tunnel-key').fill('fixture-private-runtime-key');await page.locator('#start-tunnel').click();await page.waitForFunction(()=>document.querySelector('#chain-tunnel').textContent.includes('READY'));assert.equal(await page.locator('#tunnel-key').inputValue(),'');assert(!JSON.stringify((await rpc('snapshot')).data).includes('fixture-private-runtime-key'));assert(await page.locator('#proxy-mode').isDisabled());await capture('scene-tunnel');await page.locator('#stop-tunnel').click();await refresh();assert.equal((await rpc('snapshot')).data.tunnel.running,false);});
 await check('settings persist all effect levels and reduced motion is honored',async()=>{await go('settings');await page.locator('#effects-select').selectOption('off');await page.waitForFunction(()=>document.body.classList.contains('fx-off'));await sleep(150);assert.equal((await rpc('snapshot')).data.settings.effects,'off');const a=await page.locator('#scene').evaluate(c=>c.toDataURL());await sleep(200);const b=await page.locator('#scene').evaluate(c=>c.toDataURL());assert.equal(a,b);await page.locator('#effects-select').selectOption('standard');await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>document.body.classList.contains('fx-low'));await page.emulateMedia({reducedMotion:'no-preference'});await page.locator('#setting-output').selectOption('1048576');await page.locator('#settings-form button[type="submit"]').click();await refresh();await capture('scene-settings');});
 await check('MCP stop and restart remain functional',async()=>{await page.locator('#mcp-control').click();await refresh();assert.equal((await rpc('snapshot')).data.mcp.running,false);await page.locator('#mcp-control').click();await refresh();assert.equal((await rpc('snapshot')).data.mcp.running,true);});
 await check('narrow gate folds and new approval automatically opens it',async()=>{await close();await page.setViewportSize({width:960,height:680});await page.locator('#gate-collapse').click();assert(await page.locator('#gate-rail').isVisible());const r=(await rpc('submit_local',['dev','printf narrow','窄窗审批测试','',300])).data;await refresh();await page.waitForFunction(()=>document.querySelector('#gate').classList.contains('open'));await capture('scene-minimum-window');await rpc('reject',[r.request_id]);await refresh();});
 await check('all drawers fit 960px window and 130 percent text scale',async()=>{for(const name of ['connections','requests','files','sessions','tunnel','settings']){await go(name);const dims=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert(dims.scroll<=dims.width+1,name+' overflow');}await page.locator('#ui-scale').fill('130');await page.locator('#settings-form button[type="submit"]').click();await refresh();assert.equal((await rpc('snapshot')).data.settings.scale_percent,130);for(const name of ['connections','requests','files','sessions','tunnel','settings']){await go(name);const dims=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert(dims.scroll<=dims.width+1,'scaled '+name+' overflow');}});
 await close();await page.setViewportSize({width:1400,height:900});
 await check('window blur and pointer leave cancel hold before approval',async()=>{
  const r=(await rpc('submit_local',['dev','printf cancellation','取消按住测试','',300])).data;await refresh();const b=page.locator(`[data-request-id="${r.request_id}"] .hold`);await b.waitFor();await page.waitForFunction(id=>!document.querySelector(`[data-request-id="${id}"] .hold`).disabled,r.request_id);
  const box=await b.boundingBox();await page.mouse.move(box.x+30,box.y+15);await page.mouse.down();await sleep(150);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await sleep(700);await page.mouse.up();assert.equal((await rpc('snapshot')).data.requests.find(x=>x.request_id===r.request_id).status,'pending_approval');
  await page.mouse.move(box.x+30,box.y+15);await page.mouse.down();await sleep(150);await page.mouse.move(20,20);await sleep(700);await page.mouse.up();assert.equal((await rpc('snapshot')).data.requests.find(x=>x.request_id===r.request_id).status,'pending_approval');await rpc('reject',[r.request_id]);await refresh();
 });
 await check('live secrets are masked across key blocks while selection copies raw text',async()=>{
  // Testing a connection now focuses that server; inspect all servers for output checks.
  if(await page.locator('#focus-clear').count())await page.locator('#focus-clear').click();
  const r=(await rpc('submit_local',['dev','printf secret-output','脱敏与复制测试','',300])).data;await refresh();await hold(r.request_id,1400);await waitStatus(r.request_id,'succeeded');await page.waitForFunction(()=>document.querySelector('#term').textContent.includes('ordinary line'));
  const text=await page.locator('#term').textContent();assert(!text.includes('fixture-secret-value'));assert(!text.includes('short sensitive line'));assert(text.includes('••••'));
  const copied=await page.evaluate(()=>{const row=[...document.querySelectorAll('#term [data-line]')].find(r=>r.textContent.includes('token=••••'));const selection=getSelection(),range=document.createRange();range.selectNodeContents(row.querySelector('.line-text'));selection.removeAllRanges();selection.addRange(range);const data=new DataTransfer();document.querySelector('#term').dispatchEvent(new ClipboardEvent('copy',{bubbles:true,cancelable:true,clipboardData:data}));selection.removeAllRanges();return data.getData('text/plain');});assert.equal(copied,'token=fixture-secret-value');
 });
 await check('repeat output collapses and detailed output pagination still works',async()=>{
  const r=(await rpc('submit_local',['dev','printf long-output','分页输出测试','',300])).data;await refresh();await hold(r.request_id,1400);await waitStatus(r.request_id,'succeeded');
  // STDERR can arrive between output pages: each consecutive run must retain its exact count.
  await page.waitForFunction(()=>{const runs=[...document.querySelectorAll('#term .out')].filter(r=>r.textContent.startsWith('line /'));return runs.length<=3&&runs.reduce((sum,row)=>sum+Number(row.querySelector('.rep')?.textContent.replace(/\D/g,'')||1),0)===1200;});
  await page.evaluate(id=>window.SSHUI.go('requests'),r.request_id);await page.locator(`[data-action="select-request"][data-id="${r.request_id}"]`).click();await page.locator('[data-action="output-next"]:not([disabled])').waitFor();await page.locator('[data-action="output-next"]').click();await page.waitForFunction(()=>document.querySelector('.output-toolbar').textContent.includes('32768'));await page.locator('[data-action="output-prev"]').click();await page.waitForFunction(()=>document.querySelector('.output-toolbar').textContent.includes('0–32768'));await close();
 });
 await check('900 unique output rows keep terminal and terrain buffers bounded',async()=>{
  const r=(await rpc('submit_local',['dev','printf unique-output','有界输出测试','',300])).data;await refresh();await hold(r.request_id,1400);await waitStatus(r.request_id,'succeeded');await page.waitForFunction(()=>document.querySelector('#term').textContent.includes('unique row 899'));const d=await page.evaluate(()=>window.SSHUI.diagnostics());assert(d.lineCount<=500);assert(d.terrainRows<=80);assert(!(await page.locator('#term').textContent()).includes('unique row 0\n'));assert.equal(await page.locator('#term img').count(),0);await capture('scene-terminal-output');
 });
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'ui-test-result.json'),JSON.stringify({passed:checks.length,checks,page_errors:errors,engine:await browser.version(),backend:'unchanged DesktopAPI; fixture SSH and Tunnel'},null,2));console.log('UI TESTS PASSED '+checks.length);
})().catch(async e=>{console.error(e);if(page){await page.screenshot({path:path.join(output,'failure.png')}).catch(()=>{});fs.writeFileSync(path.join(output,'failure-details.json'),JSON.stringify({checks,errors,message:String(e)},null,2));}process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();child.stdin.end();setTimeout(()=>child.kill(),1000).unref();if(fs.existsSync(html))fs.unlinkSync(html);});
