import type {ConnectionEvent} from './connection';
export type Effects='off'|'low'|'standard';
export type Drawer='requests'|'connections'|'files'|'sessions'|'tunnel'|'settings';
export type Status='pending_approval'|'queued_readonly'|'queued_authorized'|'running'|'succeeded'|'failed'|'denied'|'expired'|'timed_out'|'disconnected'|'terminated'|'termination_unconfirmed';
export interface Server {id:string; label:string; ssh_target:string; default_cwd:string; port:number|null; identity_file:string; ssh_config_file:string; auto_categories:string[]; auto_roots:string[]; auto_grant_capabilities?:string[];github_hosts?:string[]; kind?:'ssh'|'local'; workspace_roots?:string[]; connected:boolean; last_diagnostics?:{success?:boolean; hostname?:string; error?:string; checked_at?:string}}
export interface RequestSummary {request_id:string; server_id:string; server_label:string; reason:string; command_preview:string; status:Status; approval_kind:string|null; created_at:string; approved_at:string|null; finished_at:string|null; exit_code:number|null; error:string|null; output_bytes:number; operation:string; connection_event_seq?:number; phase:string; progress_bytes:number; runtime_seconds:number; last_output_at:string|null; pid:number|null; pgid:number|null; termination_requested:boolean; approval_expires_in_seconds:number;approval_remaining_ms?:number;approval_timeout_seconds?:number;grant_id?:string}
export interface SSHSettings {username:string; hostname:string; port:number; known_hosts_files:string[]; jump_hosts?:{host_alias?:string; hostname:string; username:string; port:number}[]}
export interface FileEntry {name:string; path:string; type:string; size_bytes?:number}
export interface Result {entries?:FileEntry[]; matches?:FileEntry[]; path?:string; root?:string; next_offset?:number; has_more?:boolean; eof?:boolean; text?:string; [key:string]:unknown}
export interface RequestDetail extends RequestSummary {workspace_roots?:string[]; local_shell?:string; connection_trace_version?:number; connection_events?:ConnectionEvent[]; connection_events_dropped?:number; command:string; cwd:string; timeout_seconds:number; ssh_settings:SSHSettings; digest:string; readonly_eligible:boolean; readonly_explanation:string; executed_command:string; remote_command:string; stdout:string; stderr:string; stdout_length:number; stderr_length:number; output_offset:number; next_output_offset:number; has_more_output:boolean; output_truncated:boolean; result:Result|null; total_bytes:number|null; termination?:{state?:string;remote_group_terminated?:boolean}; phase_history?:{phase:string;at:string}[]}
export interface Transfer {transfer_id:string; file_name:string; direction:'upload'|'download'; size_bytes:number; received_bytes:number; complete:boolean; sha256:string}
export interface Session {session_id:string;server_id:string;cwd:string;revision:number;environment_keys:string[];environment?:Record<string,string>}
export interface ProxyCandidate {url:string;source:string;authenticated:boolean;usable:boolean;tcp:boolean;error?:string}
export interface ProxyResult {candidates?:ProxyCandidate[];warnings?:string[];ok?:boolean;message?:string;error?:string;phase?:string;http_status?:number;duration_ms?:number;route?:{url:string;source:string}}
export interface Tunnel {running:boolean;ready:boolean;api_key_saved:boolean;id:string;health_port:number;client_path:string;client_exists:boolean;exit_code:number|null;download_status:string;download_error:string;logs:string[];ready_observed_at:number|null;proxy_mode:'auto'|'manual'|'direct';proxy_url:string;proxy_route?:{url:string;source:string};proxy_diagnostics?:{state:string;kind:string;phase?:string;result?:ProxyResult;finished_at?:number}}
export interface Settings {listen_port:number;auto_allow_readonly:boolean;approval_timeout_seconds:number;max_command_timeout_seconds:number;output_limit_bytes:number;motion_enabled:boolean;scale_percent:number;effects?:Effects;config_path:string}
export interface Prompt {id:string;kind:'credentials'|'host_key';data:{hostname:string;username:string;port:number;role?:string;host_alias?:string;attempt?:number;key_type?:string;fingerprint?:string;known_hosts_file?:string}}
export interface Authorization {grant_id:string;request_id:string;server_id:string;repo_path:string;capabilities:string[];exact_commands:string[];command_patterns?:string[];status:'granted'|'revoked'|'expired'|'exhausted';remaining_uses:number;max_uses:number;expires_in_seconds:number;max_timeout_seconds:number;git_remote:string;git_branch:string}
export interface Snapshot {version:string;uptime_seconds:number;mcp:{running:boolean;error:string;port:number;endpoint:string;calls_received?:number;calls_answered?:number};tunnel:Tunnel;servers:Server[];requests:RequestSummary[];transfers:Transfer[];sessions:Session[];authorizations:Authorization[];prompt:Prompt|null;settings:Settings}
export interface Profiles {profiles:{alias:string}[];config_path?:string;error?:string}
export interface Route {config_source?:string;route:{host_alias:string;hostname:string;username:string;port:number;identity_files:string[];identities_only:boolean;proxy_command:boolean}[]}
export interface Line {id:number;server:string;request:string;kind:'cmd'|'out'|'err'|'meta'|'ok'|'warn';raw:string;count:number;at:number;animate:boolean;privateKey?:boolean}
export interface ContextMenu {server:string;x:number;y:number}
export interface WindowState {custom_frame:boolean;maximized:boolean}
export interface TerminalInfo {available:boolean;shell:string;build:number;reason:string}
export interface TerminalChunk {data:string;offset:number;next:number;skipped:number;more:boolean;running:boolean;exit_code:number|null}
export type Modal={kind:'connection';server?:string;policy?:boolean;local?:boolean}|{kind:'command';server?:string}|{kind:'upload';transfer:Transfer}|{kind:'session';id?:string;server?:string}|{kind:'session-command';id:string}|{kind:'confirm';title:string;text:string;run:()=>Promise<unknown>}|null;
